import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Iron Goose",
  description: "Generated by create next app",
  openGraph: {
    title: "Iron Goose",
    description: "Generated by create next app",
    images: [
      {
        url: "/logo.png", // This file must be in your public/ folder
        width: 1200,
        height: 630,
        alt: "Iron Goose Website Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image", // Forces a large, wide image preview
    title: "Iron Goose",
    description: "Generated by create next app",
    images: ["/logo.png"],
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
